name: 1.2$(rev:.r) # build numbering format

variables:
  BuildConfiguration: 'Release'
  FolderToPack: 'Application'
  SolutionName: 'MLH.DockerExtensions.sln'
  ApplicationSubPath: 'MLH.DockerExtensions'
  ReSharperSettingsFileName: 'CISettings_NuGet.DotSettings'

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishToNuGet'
  displayName: 'Build and publish to NuGet'
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - checkout: ALMStuff
  - task: Docker@2
    displayName: "Start SQL Server Container"
    inputs:
      containerRegistry: DockerHub
      command: run
      arguments: '-e "ACCEPT_EULA=Y" -e "SA_PASSWORD=sTronkpassword54322!" -p 1437:1433 --name SQLServer2017 -d mcr.microsoft.com/mssql/server:2017-latest'
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Initialize_And_Test.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)
      SolutionName: $(SolutionName)
      ApplicationSubPath: $(ApplicationSubPath)
      ReSharperSettingsFileName: $(ReSharperSettingsFileName)
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Pack_And_Publish_To_NuGet.yaml@ALMStuff
    parameters:
      FolderToPack: $(FolderToPack)